# web server
nginx:
  image: nginx:latest
  ports:
    - "80:80"
    - "443:443"
  volumes:
    # app
    # - ./app/src:/usr/share/nginx/html
    # local app filder
    - /Users/master/PhpstormProjects:/usr/share/nginx
    # nginx configs
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
    # certificates
    - ./nginx/ca/server.crt/:/etc/nginx/server.crt:ro
    - ./nginx/ca/server.key/:/etc/nginx/server.key:ro
  links:
    - fpm:__DOCKER_PHP_FPM__

# php-fpm
fpm:
  build: ./php-fpm
  ports:
    - "9000"
  volumes:
   # - ./app/src:/usr/share/nginx/html
   # local app filder
    - /Users/master/PhpstormProjects:/usr/share/nginx
    # Your php.ini
    - ./php-fpm/php.ini-production:/usr/local/etc/php/php.ini:ro
    - ./mysql/mysql_sock:/var/run/mysqld
  # environment:
    # Set your APP env variables here:
    # - APP_KEY=
    # - DB_HOST=
    # - DB_DATABASE=
    # - DB_USERNAME=
    # - DB_PASSWORD=
  links:
    - mysql:mysql
    - redis:redis


# database
mysql:
  image: mysql:latest
  ports:
    # Allow client to access 3306
    - "3306:3306"
  volumes:
    # NOTE: your data will be stored in ./mysql
    - ./mysql:/var/lib/mysql
    - ./mysql/mysql_sock:/var/run/mysqld
  environment:
    - MYSQL_ROOT_PASSWORD=your_mysql_password
#redis
redis:
  image: redis
  ports:
    - "6379:6379"

#memcached
memcached:
  image: memcached
  ports:
    - "11211:11211"

